# STT 語音轉文字配置
stt:
  # 基本設定
  enabled: true
  language: "zh-TW"  # zh-TW, zh-CN, en, ja, ko
  model: "tiny"      # tiny, base, small, medium, large, large-v2, large-v3
  
  # 音頻設定
  sample_rate: 16000
  chunk_size: 1024
  
  # 語音檢測設定
  silero_sensitivity: 0.05        # 語音活動檢測靈敏度 (0.0-1.0, 越低越敏感)
  webrtc_sensitivity: 3           # WebRTC VAD 靈敏度 (0-3)
  post_speech_silence_duration: 0.5  # 語音後靜音時長 (秒)
  min_length_of_recording: 0.1    # 最短錄音時長 (秒)
  min_gap_between_recordings: 0.0 # 錄音間最短間隔 (秒)
  
  # 即時轉錄設定
  enable_realtime_transcription: true  # 啟用即時轉錄
  realtime_processing_pause: 0.02      # 即時處理間隔 (秒)
  realtime_model_type: "base"          # 即時轉錄使用的模型
  
  # GPU 設定
  use_gpu: true                    # 是否使用 GPU 加速
  gpu_device_index: null           # GPU 設備索引 (null = 自動選擇)
  
  # 進階設定
  beam_size: 5                     # Beam search 大小
  initial_prompt: null             # 初始提示文字
  
  # 喚醒詞設定 (可選)
  wake_words: []                   # 喚醒詞列表，如: ["嘿露西婭", "你好"]
  wake_words_sensitivity: 0.6      # 喚醒詞靈敏度
  
  # 自動回應設定
  auto_response: true              # 是否自動生成 AI 回應
  
  # 模型路徑 (可選，使用自訂模型)
  faster_whisper_custom_model_path: null
